const LEGACY_KEY='phantomExclusiveDrops_v3',UNIT_VALUE=2000;
let drops=[];let adminSecret=sessionStorage.getItem('phantomAdminSecret')||'';
function money(n){if(n==null)return '—';const v=Number(n);return `${v>0?'+':v<0?'-':''}$${Math.abs(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function oddsText(o){if(o==null||o==='')return '—';const n=Number(o);return n>0?`+${n}`:`${n}`}
function splitPlay(raw){const parts=raw.split(/\s+[—-]\s+/);return {play:(parts.shift()||'Exclusive Play').trim(),detail:parts.join(' — ').trim()}}
function calc(result,units,odds){const risk=(Number(units)||5)*UNIT_VALUE;if(result==='PENDING')return null;if(result==='PUSH')return 0;if(result==='LOSS')return -risk;const o=Number(odds);if(!o)return null;return Math.round((o<0?risk*100/Math.abs(o):risk*o/100)*100)/100}
function preview(){const u=Number(unitsInput.value)||5,o=Number(oddsInput.value),risk=u*UNIT_VALUE;riskPreview.textContent=`${u}U ($${risk.toLocaleString()})`;oddsPreview.textContent=oddsInput.value?oddsText(o):'—';winPreview.textContent=o?money(calc('WIN',u,o)):'—';lossPreview.textContent=money(-risk)}
function render(){adminRows.innerHTML=drops.map(x=>`<article class="admin-row"><div class="meta"><strong>${x.play}${x.detail?' — '+x.detail:''}</strong><small>${x.date} • ${x.result} • ${money(x.profit)}</small></div><div class="odds">${oddsText(x.odds)}</div><div class="units">${x.units}U</div><div><span class="badge ${x.result.toLowerCase()}">${x.result}</span></div><div class="actions"><button onclick="settle('${x.id}','WIN')">WIN</button><button onclick="settle('${x.id}','LOSS')">LOSS</button><button onclick="settle('${x.id}','PUSH')">PUSH</button><button onclick="editDrop('${x.id}')">EDIT</button><button class="del" onclick="delDrop('${x.id}')">DELETE</button></div></article>`).join('')}
async function api(body=null){if(!adminSecret){adminSecret=prompt('Enter your Command Center admin secret:')||'';sessionStorage.setItem('phantomAdminSecret',adminSecret)}const opt={headers:{'x-admin-secret':adminSecret}};if(body){opt.method='POST';opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(body)}const r=await fetch('/api/admin-drops',opt);const data=await r.json();if(r.status===401){sessionStorage.removeItem('phantomAdminSecret');adminSecret='';throw new Error('Wrong admin secret. Refresh and try again.')}if(!r.ok)throw new Error(data.error||'Server error');drops=data.drops||drops;render();return data}
async function load(){try{await api();const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(Array.isArray(legacy)&&legacy.some(x=>x.result==='PENDING')&&!drops.some(x=>x.result==='PENDING')){if(confirm('I found your existing active play in this browser. Move your existing plays into the new server-backed site so buyers can see them after purchase?'))await api({action:'replaceAll',drops:legacy});}}catch(e){alert(e.message)}}
window.settle=async(id,result)=>{const x=drops.find(v=>String(v.id)===String(id));if(result==='WIN'&&!Number(x?.odds)){const o=prompt('Enter American odds (example -116):',x?.odds??'');if(o===null)return;if(!Number(o)){alert('Odds are required for a win.');return}await api({action:'edit',id,patch:{odds:Number(o)}})}await api({action:'settle',id,result,date:new Date().toISOString().slice(0,10)})};
window.delDrop=async id=>{if(confirm('Delete this Exclusive Play?'))await api({action:'delete',id})};
window.editDrop=async id=>{const x=drops.find(v=>String(v.id)===String(id));if(!x)return;const raw=prompt('Play / matchup',`${x.play}${x.detail?' — '+x.detail:''}`);if(raw===null)return;const o=prompt('American odds',x.odds??'');if(o===null)return;const u=prompt('Units',x.units);if(u===null)return;const sp=splitPlay(raw);await api({action:'edit',id,patch:{play:sp.play,detail:sp.detail,odds:o===''?null:Number(o),units:Number(u)||5}})};
addPlay.onclick=async()=>{try{const raw=playInput.value.trim();if(!raw){alert('Enter the actual play first.');return}const result=resultInput.value,units=Number(unitsInput.value)||5,odds=oddsInput.value===''?null:Number(oddsInput.value);if(result==='WIN'&&!odds){alert('Odds are required to calculate a winning profit.');return}const sp=splitPlay(raw);await api({action:'add',drop:{date:dateInput.value||new Date().toISOString().slice(0,10),play:sp.play,detail:sp.detail,odds,units,result}});playInput.value='';oddsInput.value='';resultInput.value='PENDING';preview()}catch(e){alert(e.message)}};
oddsInput.addEventListener('input',preview);unitsInput.addEventListener('change',preview);preview();load();
