const KEY='phantomExclusiveDrops_v3',UNIT_VALUE=2000;
const seed=[
{id:2,date:'2026-08-12',play:'Rockies vs Diamondbacks',detail:'Over 9.5 Runs',odds:-116,units:5,result:'WIN',profit:8620.69},
{id:3,date:'2026-08-11',play:'Cubs vs Nationals',detail:'Over 9.5 Runs',odds:-117,units:5,result:'WIN',profit:8547.01},
{id:4,date:'2026-08-10',play:'Braves vs Mets',detail:'Over 8.5 Runs',odds:-108,units:5,result:'WIN',profit:9259.26}
];
function get(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||seed}catch{return seed}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d));render()}
function calc(result,units,odds){const risk=(Number(units)||5)*UNIT_VALUE;if(result==='PENDING')return null;if(result==='PUSH')return 0;if(result==='LOSS')return -risk;const o=Number(odds);if(!o)return null;return Math.round((o<0?risk*100/Math.abs(o):risk*o/100)*100)/100}
function money(n){if(n==null)return '—';const v=Number(n);return `${v>0?'+':v<0?'-':''}$${Math.abs(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function oddsText(o){if(o==null||o==='')return '—';const n=Number(o);return n>0?`+${n}`:`${n}`}
function splitPlay(raw){const parts=raw.split(/\s+[—-]\s+/);return {play:(parts.shift()||'Exclusive Play').trim(),detail:parts.join(' — ').trim()}}
function preview(){const u=Number(unitsInput.value)||5,o=Number(oddsInput.value),risk=u*UNIT_VALUE;riskPreview.textContent=`${u}U ($${risk.toLocaleString()})`;oddsPreview.textContent=oddsInput.value?oddsText(o):'—';winPreview.textContent=o?money(calc('WIN',u,o)):'—';lossPreview.textContent=money(-risk)}
function render(){adminRows.innerHTML=get().map((x,i)=>`<article class="admin-row"><div class="meta"><strong>${x.play}${x.detail?' — '+x.detail:''}</strong><small>${x.date} • ${x.result} • ${money(x.profit)}</small></div><div class="odds">${oddsText(x.odds)}</div><div class="units">${x.units}U</div><div><span class="badge ${x.result.toLowerCase()}">${x.result}</span></div><div class="actions"><button onclick="settle(${i},'WIN')">WIN</button><button onclick="settle(${i},'LOSS')">LOSS</button><button onclick="settle(${i},'PUSH')">PUSH</button><button onclick="editDrop(${i})">EDIT</button><button class="del" onclick="delDrop(${i})">DELETE</button></div></article>`).join('')}
window.settle=(i,result)=>{const d=get(),x=d[i];if(result==='WIN'&&!Number(x.odds)){const o=prompt('Enter American odds (example -116):',x.odds??'');if(o===null)return;if(!Number(o)){alert('Odds are required for a win.');return}x.odds=Number(o)}x.result=result;x.profit=calc(result,x.units,x.odds);if(!x.date)x.date=new Date().toISOString().slice(0,10);save(d)};
window.delDrop=i=>{if(!confirm('Delete this Exclusive Play?'))return;const d=get();d.splice(i,1);save(d)};
window.editDrop=i=>{const d=get(),x=d[i];const raw=prompt('Play / matchup',`${x.play}${x.detail?' — '+x.detail:''}`);if(raw===null)return;const o=prompt('American odds',x.odds??'');if(o===null)return;const u=prompt('Units',x.units);if(u===null)return;const sp=splitPlay(raw);x.play=sp.play;x.detail=sp.detail;x.odds=o===''?null:Number(o);x.units=Number(u)||5;x.profit=calc(x.result,x.units,x.odds);save(d)};
addPlay.onclick=()=>{const raw=playInput.value.trim();if(!raw){alert('Enter the actual play first.');return}const result=resultInput.value,units=Number(unitsInput.value)||5,odds=oddsInput.value===''?null:Number(oddsInput.value);if(result==='WIN'&&!odds){alert('Odds are required to calculate a winning profit.');return}const sp=splitPlay(raw),d=get();d.unshift({id:Date.now(),date:dateInput.value||new Date().toISOString().slice(0,10),play:sp.play,detail:sp.detail,odds,units,result,profit:calc(result,units,odds)});save(d);playInput.value='';oddsInput.value='';resultInput.value='PENDING';preview()};
oddsInput.addEventListener('input',preview);unitsInput.addEventListener('change',preview);preview();render();
