-- Phantom Drop V8
-- Run in Supabase SQL Editor. Safe to run over the previous v7 schema.

create table if not exists public.exclusive_current (
  id integer primary key,
  sport text,
  matchup text,
  pick_text text,
  odds text,
  american_odds integer,
  units numeric default 5,
  is_live boolean default false,
  is_locked boolean default false,
  is_settled boolean default false,
  updated_at timestamptz default now()
);

alter table public.exclusive_current add column if not exists is_locked boolean default false;
alter table public.exclusive_current add column if not exists is_settled boolean default false;
alter table public.exclusive_current add column if not exists american_odds integer;
alter table public.exclusive_current add column if not exists units numeric default 5;

insert into public.exclusive_current (id, sport, matchup, pick_text, odds, american_odds, units, is_live, is_locked, is_settled)
values (1, '', '', '', '', null, 5, false, false, false)
on conflict (id) do nothing;

create table if not exists public.exclusive_results (
  id bigint generated by default as identity primary key,
  result text not null check (result in ('WIN','LOSS','PUSH')),
  sport text,
  matchup text,
  pick_text text,
  odds text,
  american_odds integer,
  units numeric default 5,
  profit numeric default 0,
  created_at timestamptz default now()
);

alter table public.exclusive_results add column if not exists american_odds integer;
alter table public.exclusive_results add column if not exists units numeric default 5;
alter table public.exclusive_results add column if not exists profit numeric default 0;

alter table public.exclusive_current enable row level security;
alter table public.exclusive_results enable row level security;

drop policy if exists "exclusive current temporary write" on public.exclusive_current;
drop policy if exists "exclusive results temporary insert" on public.exclusive_results;

drop policy if exists "exclusive current public read" on public.exclusive_current;
create policy "exclusive current public read" on public.exclusive_current for select using (true);

drop policy if exists "exclusive results public read" on public.exclusive_results;
create policy "exclusive results public read" on public.exclusive_results for select using (true);

drop policy if exists "exclusive current authenticated write" on public.exclusive_current;
create policy "exclusive current authenticated write" on public.exclusive_current for all to authenticated using (true) with check (true);

drop policy if exists "exclusive results authenticated insert" on public.exclusive_results;
create policy "exclusive results authenticated insert" on public.exclusive_results for insert to authenticated with check (true);
