-- V3 schema / migration
create table if not exists public.exclusive_current (
  id integer primary key,
  sport text,
  matchup text,
  pick_text text,
  odds text,
  is_live boolean default false,
  is_locked boolean default false,
  is_settled boolean default false,
  updated_at timestamptz default now()
);

alter table public.exclusive_current add column if not exists is_locked boolean default false;
alter table public.exclusive_current add column if not exists is_settled boolean default false;

insert into public.exclusive_current (id, sport, matchup, pick_text, odds, is_live, is_locked, is_settled)
values (1, '', '', '', '', false, false, false)
on conflict (id) do nothing;

create table if not exists public.exclusive_results (
  id bigint generated by default as identity primary key,
  result text not null check (result in ('WIN','LOSS','PUSH')),
  sport text,
  matchup text,
  pick_text text,
  odds text,
  created_at timestamptz default now()
);

alter table public.exclusive_current enable row level security;
alter table public.exclusive_results enable row level security;

-- If these policies already exist from V2, leave them as-is.
-- Public prototype read/write rules should be replaced with authenticated admin policies before launch.
