-- Phantom Picks Exclusive — Red/Gold Multi-Play Upgrade
-- Safe to run on the existing Site 3 Supabase project.

create table if not exists public.exclusive_current (
  id integer primary key,
  sport text,
  matchup text,
  pick_text text,
  odds text,
  units numeric not null default 5,
  is_live boolean default false,
  is_locked boolean default true,
  is_settled boolean default false,
  updated_at timestamptz default now()
);

alter table public.exclusive_current add column if not exists is_locked boolean default true;
alter table public.exclusive_current add column if not exists is_settled boolean default false;

create table if not exists public.exclusive_results (
  id bigint generated by default as identity primary key,
  result text not null check (result in ('WIN','LOSS','PUSH')),
  sport text,
  matchup text,
  pick_text text,
  odds text,
  units numeric not null default 5,
  created_at timestamptz default now()
);

alter table public.exclusive_current enable row level security;
alter table public.exclusive_results enable row level security;

drop policy if exists "exclusive current public read" on public.exclusive_current;
create policy "exclusive current public read" on public.exclusive_current for select using (true);

drop policy if exists "exclusive results public read" on public.exclusive_results;
create policy "exclusive results public read" on public.exclusive_results for select using (true);

drop policy if exists "exclusive current authenticated write" on public.exclusive_current;
create policy "exclusive current authenticated write" on public.exclusive_current for all to authenticated using (true) with check (true);

drop policy if exists "exclusive results authenticated insert" on public.exclusive_results;
drop policy if exists "exclusive results authenticated write" on public.exclusive_results;
create policy "exclusive results authenticated write" on public.exclusive_results for all to authenticated using (true) with check (true);

alter table public.exclusive_current add column if not exists units numeric not null default 5;
alter table public.exclusive_results add column if not exists units numeric not null default 5;
